# Generated by Django 3.2.14 on 2022-07-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=50)),
                ('pathologie', models.CharField(max_length=50)),
                ('form_pharmaceatique', models.TextField(choices=[('Comprime', 'Comprime'), ('Gélule', 'Gélule'), ('Sirop / solution buvable', 'Sirop/ solution buvable'), ('Comprimé effervescent', 'Comprimé effervescent'), ('Créme', 'Créme'), ('Ampoule', 'Ampoule'), ('Granules', 'Granules'), ('Granules', 'Granules'), ('Goutte', 'Goutte'), ('Injection', 'Injection'), ('Pommade', 'Pommade'), ('Collyre', 'Collyre'), ('Pulvérisation', 'Pulvérisation'), ('Suppositoire', 'Suppositoire'), ('Sachet', 'Sachet'), ('Inhalation', 'Inhalation')], max_length=50)),
                ('nombre_comprime', models.IntegerField()),
            ],
        ),
    ]
