# Generated by Django 3.2.14 on 2022-07-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='date_de_prise',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='moment_de_prise',
            field=models.TextField(choices=[('Sans importance', 'Sans importance'), ('En dehors des repas', 'En dehors des repas'), ('Avant le repas', 'Avant le repas'), ('Pendant le repas', 'Pendant le repas'), ('A pres le repas', 'A pres le repas')], default='Sans importance', max_length=50),
            preserve_default=False,
        ),
    ]
