# Generated by Django 3.2.14 on 2022-07-20 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile_img/default.png', upload_to='profile_img/'),
        ),
    ]
